name: smartagrinet
description: Smart Agriculture Platform for African Farmers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  
  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Camera & Image Processing
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  tflite_flutter: ^0.10.4
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^23.2.7
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # QR Code & Barcode
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  
  # Offline Support
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.0
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  
  # Utilities
  uuid: ^4.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # Date & Time
  table_calendar: ^3.0.9
  timeago: ^3.6.0
  
  # Forms & Validation
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.1.1
  
  # Charts & Data Visualization
  syncfusion_flutter_gauges: ^23.2.7
  syncfusion_flutter_sliders: ^23.2.7
  
  # Voice & Speech
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  
  # Social Features
  share_plus: ^7.2.1
  
  # Weather
  weather: ^3.1.1
  
  # File Handling
  file_picker: ^6.1.1
  open_file: ^3.3.2
  
  # Network
  internet_connection_checker: ^1.0.0+1
  
  # Biometrics
  local_auth: ^2.1.7
  
  # Video Player
  video_player: ^2.8.1
  chewie: ^1.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/
    - assets/ml_models/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700 